version: '3'

services:
  php:
    container_name: php
    image: registry.cn-beijing.aliyuncs.com/duiying/php7.2:1.0
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www:/data
      - ./.log/php:/var/log/php-fpm
  nginx:
    container_name: nginx
    image: registry.cn-beijing.aliyuncs.com/duiying/nginx:1.0
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/data/www
      - ./nginx:/etc/nginx/conf.d
      - ./.log/nginx:/var/log/nginx
    depends_on:
      - php
    links:
      - php
networks:
  default: